# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janelaLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import qrcode

class Ui_BotH51(object):
    def setupUi(self, BotH51):
        BotH51.setObjectName("BotH51")
        BotH51.resize(480, 680)
        BotH51.setMinimumSize(QtCore.QSize(480, 680))
        BotH51.setMaximumSize(QtCore.QSize(480, 680))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logodescarte/1.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BotH51.setWindowIcon(icon)
        BotH51.setStyleSheet("QWidget {\n"
                             "    background-color: rgb(35,45,55);\n"
                             "\n"
                             "}")
        BotH51.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.janelaLogin = QtWidgets.QWidget(BotH51)
        self.janelaLogin.setObjectName("janelaLogin")
        self.frameignore = QtWidgets.QFrame(self.janelaLogin)
        self.frameignore.setGeometry(QtCore.QRect(115, 100, 260, 180))
        self.frameignore.setStyleSheet("background-image: url(:/logo1/Untitled-1.png);\n"
                                       "border: none;\n"
                                       "background-repeat: no-repeat;\n"
                                       "background-position: center;")
        self.frameignore.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameignore.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameignore.setObjectName("frameignore")
        self.frameLogin = QtWidgets.QFrame(self.janelaLogin)
        self.frameLogin.setGeometry(QtCore.QRect(100, 340, 281, 181))
        self.frameLogin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLogin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLogin.setObjectName("frameLogin")
        self.buttonQrcode = QtWidgets.QPushButton(self.frameLogin)
        self.buttonQrcode.setGeometry(QtCore.QRect(210, 131, 70, 35))
        font = QtGui.QFont()
        font.setFamily("Cocogoose Pro")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.buttonQrcode.setFont(font)
        self.buttonQrcode.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonQrcode.setStyleSheet("background-color: rgb(255, 255, 100);\n"
                                        "color: rgb(35,45,55);")
        self.buttonQrcode.setObjectName("buttonQrcode")
        self.lineUsuario = QtWidgets.QLineEdit(self.frameLogin)
        self.lineUsuario.setGeometry(QtCore.QRect(0, 10, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Cocogoose Pro")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.lineUsuario.setFont(font)
        self.lineUsuario.setStyleSheet("QLineEdit {\n"
                                       "    background-color: rgb(230,245,245);\n"
                                       "    padding: 10px;\n"
                                       "    color: rgb(35,45,55);\n"
                                       "}\n"
                                       "QLineEdit:hover {\n"
                                       "    background-color: rgb(255,255,100);\n"
                                       "    border: 3px solid rgb(255,255,100);\n"
                                       "    padding: 10px;\n"
                                       "    color: rgb(35,45,55);\n"
                                       "}\n"
                                       "")
        self.lineUsuario.setInputMask("")
        self.lineUsuario.setText("")
        self.lineUsuario.setObjectName("lineUsuario")
        self.salvarlogin = QtWidgets.QCheckBox(self.frameLogin)
        self.salvarlogin.setGeometry(QtCore.QRect(0, 130, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.salvarlogin.setFont(font)
        self.salvarlogin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.salvarlogin.setStyleSheet("QCheckBox:hover {\n"
                                       "    color: rgb(255, 255, 100);\n"
                                       "}\n"
                                       "QCheckBox {\n"
                                       "    color: rgb(213,240,237);\n"
                                       "}\n"
                                       "")
        self.salvarlogin.setObjectName("salvarlogin")
        self.buttonEntrar = QtWidgets.QPushButton(self.frameLogin)
        self.buttonEntrar.setGeometry(QtCore.QRect(70, 131, 131, 35))
        font = QtGui.QFont()
        font.setFamily("Cocogoose Pro")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.buttonEntrar.setFont(font)
        self.buttonEntrar.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonEntrar.setStyleSheet("background-color: rgb(255, 255, 100);\n"
                                        "color: rgb(35,45,55);")
        self.buttonEntrar.setObjectName("buttonEntrar")
        self.lineSenha = QtWidgets.QLineEdit(self.frameLogin)
        self.lineSenha.setGeometry(QtCore.QRect(0, 70, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Cocogoose Pro")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.lineSenha.setFont(font)
        self.lineSenha.setStyleSheet("QLineEdit {\n"
                                     "    background-color: rgb(230,245,245);\n"
                                     "    padding: 10px;\n"
                                     "    color: rgb(35,45,55);\n"
                                     "}\n"
                                     "QLineEdit:hover {\n"
                                     "    background-color: rgb(255,255,100);\n"
                                     "    border: 3px solid rgb(255,255,100);\n"
                                     "    padding: 10px;\n"
                                     "    color: rgb(35,45,55);\n"
                                     "}\n"
                                     "")
        self.lineSenha.setInputMask("")
        self.lineSenha.setText("")
        self.lineSenha.setObjectName("lineSenha")
        self.frameGrupo = QtWidgets.QFrame(self.janelaLogin)
        self.frameGrupo.setGeometry(QtCore.QRect(90, 290, 300, 341))
        self.frameGrupo.setStyleSheet("background-image: url(:/qrcode/qrcode.png);\n"
                                      "background-repeat: no repeat")
        self.frameGrupo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGrupo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGrupo.setObjectName("frameGrupo")
        self.pushButton = QtWidgets.QPushButton(self.frameGrupo)
        self.pushButton.setGeometry(QtCore.QRect(100, 310, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Cocogoose Pro")
        font.setPointSize(9)
        font.setItalic(True)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 100);\n"
                                      "color: rgb(35,45,55)")
        self.pushButton.setObjectName("pushButton")
        BotH51.setCentralWidget(self.janelaLogin)

        self.retranslateUi(BotH51)
        QtCore.QMetaObject.connectSlotsByName(BotH51)

    def retranslateUi(self, BotH51):
        _translate = QtCore.QCoreApplication.translate
        BotH51.setWindowTitle(_translate("BotH51", "BotH51"))
        self.buttonQrcode.setText(_translate("BotH51", "Grupo"))
        self.lineUsuario.setPlaceholderText(_translate("BotH51", "Usuário"))
        self.salvarlogin.setText(_translate("BotH51", "Salvar"))
        self.buttonEntrar.setText(_translate("BotH51", "Entrar"))
        self.buttonEntrar.setShortcut(_translate("BotH51", "Return"))
        self.lineSenha.setPlaceholderText(_translate("BotH51", "Senha"))
        self.pushButton.setText(_translate("BotH51", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BotH51 = QtWidgets.QMainWindow()
    ui = Ui_BotH51()
    ui.setupUi(BotH51)
    BotH51.show()
    sys.exit(app.exec_())
